---
- hosts: localhost
  tasks:
  - name: "Install kubernetes python package"
    pip:
      name: kubernetes
      state: present
  - name: install mysql
    kubernetes.core.k8s:
      state: present
      src: mysql.yaml
  # - name: install gitea via helm
  #   community.kubernetes.helm:
  #     name: gitea
  #     chart_ref: gitea-charts/gitea
  #     release_namespace: default
  #     create_namespace: true
  #     values_files:
  #       - values.yaml
  - name: Add gitea chart repo
    kubernetes.core.helm_repository:
      name: gitea-charts
      repo_url: "https://dl.gitea.com/charts/"
  - name: Deploy latest version of gitea
    kubernetes.core.helm:
      name: gitea
      chart_ref: gitea-charts/gitea
      release_namespace: default
      values_files:
      - values.yaml
      values:
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: false
        redis-cluster:
          enabled: false